name: composable_architecture_router
description: A composable architecture based navigator 2.0 for flutter
version: 0.1.0
repository: https://github.com/composablearchitecture-io/flutter
topics:
  - navigation
  - composable
  - navigator
  - routing
  - state-management

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  composable_architecture_flutterw: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.21.0
